### ISSUE TITLE
test_multiprocessing_spawn fails

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#122]
The test takes **forever** to run, so be careful about running the entire test file.

======================================================================
ERROR: test_barrier (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1244,
er
    self.run_threads(self.multipass, (self.barrier, results, passes))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1229,
    barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 994, in
    return self._callmethod('wait', (timeout,))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 732, in
    raise convert_to_error(kind, result)
threading.BrokenBarrierError

======================================================================
ERROR: test_barrier_10 (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1250,
er_10
    return self.test_barrier(10)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1244,
er
    self.run_threads(self.multipass, (self.barrier, results, passes))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1229,
    barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 994, in
    return self._callmethod('wait', (timeout,))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 732, in
    raise convert_to_error(kind, result)
threading.BrokenBarrierError

======================================================================
ERROR: test_default_timeout (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1410,
lt_timeout
    self.run_threads(self._test_default_timeout_f, (barrier, results))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1395,
ult_timeout_f
    i = barrier.wait(cls.defaultTimeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 994, in
    return self._callmethod('wait', (timeout,))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 732, in
    raise convert_to_error(kind, result)
threading.BrokenBarrierError

======================================================================
ERROR: test_reset (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1332,

    (self.barrier, results1, results2, results3))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1308,
t_f
    i = barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 994, in
    return self._callmethod('wait', (timeout,))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 732, in
    raise convert_to_error(kind, result)
threading.BrokenBarrierError

======================================================================
ERROR: test_timeout (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1390,
ut
    self.run_threads(self._test_timeout_f, (self.barrier, results))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1376,
out_f
    i = barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 994, in
    return self._callmethod('wait', (timeout,))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 732, in
    raise convert_to_error(kind, result)
threading.BrokenBarrierError

======================================================================
ERROR: test_wait_return (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1262,
return
    self.run_threads(self._test_wait_return_f, (self.barrier, queue))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1254,
_return_f
    res = barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 994, in
    return self._callmethod('wait', (timeout,))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\multiprocessing\managers.py", line 732, in
    raise convert_to_error(kind, result)
threading.BrokenBarrierError

======================================================================
ERROR: test_barrier (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1244,
er
    self.run_threads(self.multipass, (self.barrier, results, passes))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1229,
    barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 619, in wait
    self._wait(timeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 657, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError

======================================================================
ERROR: test_barrier_10 (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1250,
er_10
    return self.test_barrier(10)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1244,
er
    self.run_threads(self.multipass, (self.barrier, results, passes))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1229,
    barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 619, in wait
    self._wait(timeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 657, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError

======================================================================
ERROR: test_default_timeout (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1410,
lt_timeout
    self.run_threads(self._test_default_timeout_f, (barrier, results))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1395,
ult_timeout_f
    i = barrier.wait(cls.defaultTimeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 619, in wait
    self._wait(timeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 657, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError

======================================================================
ERROR: test_reset (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1332,

    (self.barrier, results1, results2, results3))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1308,
t_f
    i = barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 619, in wait
    self._wait(timeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 657, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError

======================================================================
ERROR: test_timeout (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1390,
ut
    self.run_threads(self._test_timeout_f, (self.barrier, results))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1376,
out_f
    i = barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 619, in wait
    self._wait(timeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 657, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError

======================================================================
ERROR: test_wait_return (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1262,
return
    self.run_threads(self._test_wait_return_f, (self.barrier, queue))
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1219,
s
    f(*args)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1254,
_return_f
    res = barrier.wait()
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 619, in wait
    self._wait(timeout)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\threading.py", line 657, in _wait
    raise BrokenBarrierError
threading.BrokenBarrierError

======================================================================
FAIL: test_abort (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1303,

    self.assertEqual(len(results2), self.N-1)
AssertionError: 5 != 4

======================================================================
FAIL: test_abort_and_reset (test.test_multiprocessing_spawn.WithManagerTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1371,
_and_reset
    self.assertEqual(len(results2), self.N-1)
AssertionError: 5 != 4

======================================================================
FAIL: test_wait_result (test.test_multiprocessing_spawn.WithManagerTestCondition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1058,
result
    self.assertTrue(c.wait(10))
AssertionError: False is not true

======================================================================
FAIL: test_waitfor_timeout (test.test_multiprocessing_spawn.WithManagerTestCondition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1024,
or_timeout
    self.assertTrue(sem.acquire(timeout=10))
AssertionError: False is not true

======================================================================
FAIL: test_abort_and_reset (test.test_multiprocessing_spawn.WithProcessesTestBarrier)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1371,
_and_reset
    self.assertEqual(len(results2), self.N-1)
AssertionError: 5 != 4

======================================================================
FAIL: test_wait_result (test.test_multiprocessing_spawn.WithProcessesTestCondition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1058,
result
    self.assertTrue(c.wait(10))
AssertionError: False is not true

======================================================================
FAIL: test_waitfor_timeout (test.test_multiprocessing_spawn.WithProcessesTestCondition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 1024,
or_timeout
    self.assertTrue(sem.acquire(timeout=10))
AssertionError: False is not true

======================================================================
FAIL: test_sys_exit (test.test_multiprocessing_spawn.WithProcessesTestSubclassingProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\_test_multiprocessing.py", line 480,
it
    self.assertEqual(p.exitcode, code)
AssertionError: None != 1

----------------------------------------------------------------------
Ran 265 tests in 2991.507s

**Comment by brettcannon** [comment]
I'm still getting failures.

**Comment by brettcannon** [comment]
I realized all of these failing tests are time-based, so closing as fixed.
