### ISSUE TITLE
test_subprocess fails

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#127]
======================================================================
ERROR: test_wait_timeout (test.test_subprocess.ProcessTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_subprocess.py", line 995, in test_wait_timeout

    self.assertEqual(p.wait(timeout=3), 0)
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\subprocess.py", line 1273, in wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['C:\\Users\\brcan\\Documents\\Repositories\\Pyjion\\Python\\PCbuild\\amd64\\python_
d.exe', '-c', 'import time; time.sleep(0.3)']' timed out after 3 seconds

======================================================================
FAIL: test_check_output_timeout (test.test_subprocess.ProcessTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_subprocess.py", line 218, in test_check_output
_timeout
    self.assertEqual(c.exception.output, b'BDFL')
AssertionError: b'' != b'BDFL'

======================================================================
FAIL: test_check_output_timeout (test.test_subprocess.RunFuncTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_subprocess.py", line 1318, in test_check_outpu
t_timeout
    self.assertEqual(c.exception.output, b'BDFL')
AssertionError: b'' != b'BDFL'

----------------------------------------------------------------------

**Comment by brettcannon** [comment]
The failures are timeout-related, so I'm closing as fixed.
