### ISSUE TITLE
test_asyncio fails

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/Pyjion#135]
======================================================================
FAIL: test_log_destroyed_pending_task (test.test_asyncio.test_tasks.TaskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_asyncio\test_tasks.py", line 1693, in test_log
_destroyed_pending_task
    self.assertEqual(asyncio.Task.all_tasks(loop=self.loop), set())
AssertionError: Items in the first set but not the second:
<Task pending coro=<kill_me() running at C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_asyncio\test_
tasks.py:1666> wait_for=<Future pending cb=[Task._wakeup()] created at C:\Users\brcan\Documents\Repositories\Pyjion\Pyth
on\lib\test\test_asyncio\test_tasks.py:1665> created at C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\tes
t_asyncio\test_tasks.py:1677>

======================================================================
FAIL: test_task_repr (test.test_asyncio.test_tasks.TaskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_asyncio\test_tasks.py", line 192, in test_task
_repr
    coro_qualname)
AssertionError: 'notmuch' != 'TaskTests.test_task_repr.<locals>.notmuch'
- notmuch
+ TaskTests.test_task_repr.<locals>.notmuch

======================================================================
FAIL: test_task_repr_coro_decorator (test.test_asyncio.test_tasks.TaskTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\brcan\Documents\Repositories\Pyjion\Python\lib\test\test_asyncio\test_tasks.py", line 254, in test_task
_repr_coro_decorator
    self.assertEqual(gen.__name__, coro_name)
AssertionError: 'coro' != 'notmuch'
- coro
+ notmuch

----------------------------------------------------------------------

**Comment by brettcannon** [comment]
One of the failures is due to #86
